@BASE_URL=http://127.0.0.1:8000/api
@TOKEN=3|r69wz8yG0DMJF7toxfltOMCYRZVC89tZQcw8Y7PZc9547080
POST {{BASE_URL}}/register
Content-Type: application/json

 {
   "name": "Admin satu",
     "email": "admin@gmail.com",
     "password": "secret123",
     "password_confirmation": "secret123",
    "role": "admin"
  }
# [
#   {
#     "name": "User Satu",
#     "email": "user1@gmail.com",
#     "password": "secret123",
#     "password_confirmation": "secret123",
#     "role": "user"
#   },
#   {
#     "name": "Admin Satu",
#     "email": "admin@gmail.com",
#     "password": "secret123",
#     "password_confirmation": "secret123",
#     "role": "admin"
#   },
#   {
#     "name": "User Dua",
#     "email": "user2@gmail.com",
#     "password": "secret123",
#     "password_confirmation": "secret123",
#     "role": "user"
#   }
# ]

###LOGIN
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "tes@gmail.com",
  "password": "secret123"
}
